### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by KirilKabakchiev** [Peripli/service-manager#145]
Introduce some basic structure for documentation. Add relevant content.

- Introduction (intoduction.md)
    - Motivation (problem/solution overview)
    - This is the landing page - one can access all other subpages from here (other pages are grouped in categories in this page)
- Installation (install folder)
    - README.md (Prerequisites and links to sm.md, cf-proxy.md, k8s-proxy.md, cli.md and link to devguide/local)
    - sm.md with two sections (cf and k8s)
    - cf-proxy.md (should also include platform reg)
    - k8s-proxy.md (should also include platform reg)
- Walkthrough (walkthrough.md)
- Concepts (folder inside docs)
    - Overview (overview.md with high-level archicture diagram and explanations)
    - Components (just one components.md or seperate sm.md, agent.md, cli.md)
    - Extensibility (extentions.md, extending the service manager with custom filters, plugins and controllers)
    - Security (security.md, authn/authz?)
    - Additional Resources (resources.md with links to spec, videos, etc)
- Dev Guide (devguide.md)
    - Required to install SM DevBox(go, gnu make, git, docker, minikube with servicecatalog and helm, pcfdev with buildpack for go1.10, smctl, kubectl, svcat)
    - Repository Structure (code layout)
    - Extensibility (link to Concepts/extensibility.md)
    - Building (as binaries or into docker containers)
    - Running Tests
        - Unit
        - Integration
        - E2e
        - Coverage
   - Dependency Management (adding, updating, removing dependencies, mention vendor folder is not pushed into the repo)
    - Run Components Locally
- Code Standards
    - Code Quality
    - Coverage
    - Docs

**Comment by dzahariev** [comment]
Look like completed 👍 
https://github.com/Peripli/service-manager/pull/147
https://github.com/Peripli/service-manager/pull/148
https://github.com/Peripli/service-manager/pull/149
https://github.com/Peripli/service-manager/pull/150
https://github.com/Peripli/service-manager/pull/151
https://github.com/Peripli/service-manager/pull/152
https://github.com/Peripli/service-manager/pull/153
https://github.com/Peripli/service-manager/pull/154
https://github.com/Peripli/service-manager/pull/155
https://github.com/Peripli/service-manager/pull/156
https://github.com/Peripli/service-manager/pull/163
