### ISSUE TITLE
Improve Makefile in all repos

### ISSUE THREAD

**Issue by dpanayotov** [Peripli/service-manager#170]
Makefile can be improved in all repositories:

1. Build docker images.
2. Add version flag from commit
3. `gofmt`
4. push to k8s & cf / run locally
5. flags to `go test`
6. make release that increases the version in all necessary files, creates a tag and pushes to github

**Comment by KirilKabakchiev** [comment]
some improvements here - https://github.com/Peripli/service-manager/pull/173
