### ISSUE TITLE
Integrate pull approve

### ISSUE THREAD

**Issue by dzahariev** [Peripli/service-manager#23]
# Background
There is an online service that can check if a request is approved before allow merge:
https://about.pullapprove.com/

# Objective
1. Create a group with core team contributors that can approve pull requests
1. Integrate pullapprove.com for all repositories and define as approvers the core contributors group.

# Acceptance criteria
Each change in pull requests in all repositories should be automatically checked for approval from one of core contributors. 
The pull request should not be allowed to be merged without an approval from core contributors group  member.

**Comment by NickyMateev** [comment]
The team decided not to integrate PullApprove. We'll instead use the built-in GitHub functionality for protected branches.
