### ISSUE TITLE
Research how to store credentials in a secured way

### ISSUE THREAD

**Issue by dzahariev** [Peripli/service-manager#24]
SM need to store credentials for all registered SB and all registered platforms. Those credentials need to be stored in a secure way.
Research what are the options - key store, external modules that encrypts the persistent content or some other way, and propose the most appropriate solution to do this. 

-----
The deliverable for research task is a comprehensive comment inside the issue that provide valuable information about the researched topic. It will be very helpful to be organised a knowledge sharing session with the team on the topic, that explains the matter and provide some examples. The issue can be closed once the team agrees on the technology that shall be used for each one specific aspect.

**Comment by loewenstein** [comment]
@dzahariev Do you know https://github.com/cloudfoundry-incubator/credhub? Might be worth an evaluation.

**Comment by dzahariev** [comment]
Inside CF: https://docs.cloudfoundry.org/credhub/ 
Inside k8s “secrets” are used. https://kubernetes.io/docs/concepts/configuration/secret/
