### ISSUE TITLE
Do not return last_notification_revision 0 but skip this header

### ISSUE THREAD

**Issue by dotchev** [Peripli/service-manager#272]
When a proxy connect to SM and there are no notifications in the db, SM returns header _last_notification_revision_ 0. This is an artificial notification revision as revisions start from 1.
If the websocket connection breaks before the first notification arrives, the proxy will try to reconnect with query parameter _last_notification_revision_ 0. Then SM will return immediately status 410 Gone. This is 
necessary because in the meantime some notifications might have passed and have been deleted from the db. Then the proxy will reconnect without _last_notification_revision_ and execute a full resync.

To avoid confusion, instead of _last_notification_revision_ 0, SM could skip this header in the response. Then if the proxy needs to reconnect before the first notification, it can connect without   _last_notification_revision_ query parameter.

**Comment by dpanayotov** [comment]
Fixed with #289
