### ISSUE TITLE
Research options for persistency

### ISSUE THREAD

**Issue by dzahariev** [Peripli/service-manager#3]
Research options for persistency. 
Relational (Postgre) vs NoSQL (Mongo) vs K-V Store (ETCD) with Go. 
Implications like not supported stack - for instance K-V store is not provided out of the box on CF stack. 
SM will run on CF first, so the initial setup should consider this.

-----
The deliverable for research task is a comprehensive comment inside the issue that provide valuable information about the researched topic. It will be very helpful to be organised a knowledge sharing session with the team on the topic, that explains the matter and provide some examples. The issue can be closed once the team agrees on the technology that shall be used for each one specific aspect.

**Comment by NickyMateev** [comment]
# Research options for persistency
A relational database (*Postgres*) shall be used for the initial implementation of the **Service Manager**. The decision is based on the fact that the current database model backing the **Service Manager** is best fitted for a relation database.

There's a lot of options for components like database drivers and tools, which enhance the workflow when developing Go applications which use relational databases. The same cannot be said for NoSQL databases or some other key-value store.

[A curated list of awesome Go storage projects and libraries.][1]

[1]: https://github.com/gostor/awesome-go-storage
