### ISSUE TITLE
REST API research

### ISSUE THREAD

**Issue by dzahariev** [Peripli/service-manager#5]
Evaluate and compare net/http package vs (router) frameworks - julienschmidt/httprouter, gorilla/mux vs full fledged web frameworks - gin-gonic/gin, astaxie/beego, labstack/echo or others?

Some useful links:
https://nordicapis.com/7-frameworks-to-build-a-rest-api-in-go/
https://blog.usejournal.com/top-6-web-frameworks-for-go-as-of-2017-23270e059c4b

-----
The deliverable for research task is a comprehensive comment inside the issue that provide valuable information about the researched topic. It will be very helpful to be organised a knowledge sharing session with the team on the topic, that explains the matter and provide some examples. The issue can be closed once the team agrees on the technology that shall be used for each one specific aspect.

**Comment by NickyMateev** [comment]
# Rest API research 

For the initial implementation we'll use the HTTP Multiplexer **Gorilla Mux**. Our decision is based on the following bullet points:

## HTTP Multiplexer vs. Web Framework:
For the initial implementation service manager will not have a UI so having a full fledged web framework will have a negative impact on development. Most web frameworks could lead to performance decreases compared to a plain HTTP Multiplexer.

## Third-party Multiplexer vs. The standard **http.ServeMux**
A third-party multiplexer alleviates the effort of implementing logic for matching path variables, subrouting, middleware support, etc. 

## Why Gorilla Mux?
Gorilla Mux is a well-known HTTP Multiplexer, which provides essential features and has a good community support.
