### ISSUE TITLE
Support for Instance Sharing

### ISSUE THREAD

**Issue by joshianurag21** [Peripli/service-manager#637]
# Description

I am exploring Peripli. On [example scenarios](https://github.com/Peripli/service-manager/blob/master/docs/usage/example-usage.md) page, there is a note saying instance sharing is planned, but not yet available. Can you please provide approximate timeline for this instance sharing feature to be available in Peripli.

[1]: https://github.com/Peripli
  [2]: service-manager-wg@googlegroups.com

**Comment by EpsilonTal** [comment]
The feature has been delivered https://github.com/Peripli/service-manager/pull/631
