### ISSUE TITLE
Research Logging frameworks

### ISSUE THREAD

**Issue by dzahariev** [Peripli/service-manager#8]
sirupsen/logrus vs golang/glog vs cloudfoundry/lager vs others? 
Requirement is to be able:
- To switch log levels without redeploying
- To have different log levels for different packages
- Support to change format, so we can easily integrate with Kibana.
- Format switching with profile or property (local mode and cloud mode).
- Stack trace libraries (to make logs meaningful) - palantir/stacktrace vs others?

-----
The deliverable for research task is a comprehensive comment inside the issue that provide valuable information about the researched topic. It will be very helpful to be organised a knowledge sharing session with the team on the topic, that explains the matter and provide some examples. The issue can be closed once the team agrees on the technology that shall be used for each one specific aspect.

**Comment by dpanayotov** [comment]
For the initial implementation we'll use **[logrus](https://github.com/sirupsen/logrus)**.

- Different log levels for different packages:
    - https://github.com/coreos/pkg/tree/master/capnslog has something similar. We could have `logger` package with `func New(packageName string) *logrus.Logger` and `func SetPackageLogLevel(packageName, level string)`
    - Log level can be specified pre-deploy per package by having a configuration file with property `log.level.<package_name>` If no explicit log level for the package is specified, then the value of the property `log.level` will be taken. The default value for this property is TBD.
- Change log level withoud redeploying:
    - We can change log level when the application is restarted 
    - Changing log level without restarting: The analog would be Spring Boot Actuator where you get an endpoint for switching log level. We could make such "management" extension for Go but for now, it's out of scope. By utilizing the above `SetLevel` function we can change dynamically the log level
- Support to change the format:
    - Logrus has two formats - Text and JSON. This can also be configured per logger.
- Format switching:
    - Configuration can be externalized and can be read on start-up. So a `log.format` property can be provided. Profiles in the Spring sense are out of scope currently
- Meaningful logs:
    - This does not directly concern the logging library. There's no stacktrace support built-in if you want to propagate the error to an upper level. One option is to use https://github.com/pkg/errors which gives the ability to chain errors and see the execution path as shown in the example https://github.com/pkg/errors/blob/master/example_test.go#L20
