### ISSUE TITLE
Introduce explicit filter / plugin ordering

### ISSUE THREAD

**Issue by KirilKabakchiev** [Peripli/service-manager#98]
In the future in order to easen filter registration it might be necessary to introduce explicit filter ordering (e.g.  each filter to have a number accosiated with it that specifies its order). Currently ordering depends on the order filters are added to a list.

**Comment by dpanayotov** [comment]
For simplicity the current proposal is to have filter/plugin registration before/after another filter/plugin and replacing a specific filter/plugin with another

**Comment by dpanayotov** [comment]
Closed with #108
